data:
  csv_path: "data/ip_addresses_sample/agg_10_minutes/11.csv"
  test_size: 0.2
  random_state: 42

execution_mode: "test"  # Options: "train", "test", "evaluate"

quantum:
  type: "discrete"  # or "continuous"
  n_qubits: 4      # for discrete QNN
  n_layers: 2
  n_qumodes: 4     # for continuous QNN
  cutoff_dim: 10   # for continuous QNN

qnn_architecture:
  architecture: [3, 6, 3]  # Example: Input, hidden, and output layer sizes

training:
  batch_size: 128  # Adjusted for larger dataset
  epochs: 30
  learning_rate: 0.001
  early_stopping_patience: 5
  min_delta: 0.001
  log_interval: 5
  resume_training: false  # Set to true to resume from checkpoint
  checkpoint_interval: 10  # Save checkpoint every N epochs

anomaly:
  threshold: 0.5
  percentile: 95

zero_trust:
  risk_threshold: 0.5
  segment_threshold: 0.2

visualization:
  plot_interval: 10  # Plot every N epochs
