in_features: 13
num_classes: 3
n_layers: 3
layer_widths: [10,8, 6]
cutoff_dim: 5
num_epochs: 20
batch_size: 128
learning_rate: 0.001
train_size: 256
num_samples: 128 
checkpoint_dir: "checkpoints"
plots_dir: "plots"
checkpoint_frequency: 5
data:
  base_path: "../data"
  folder_path: "ip_addresses_sample/agg_10_minutes"
  feature_columns: [
    'id_time', 'n_flows', 'n_packets', 'n_bytes', 'n_dest_asn', 
    'n_dest_ports', 'n_dest_ip', 'tcp_udp_ratio_packets', 
    'tcp_udp_ratio_bytes', 'dir_ratio_packets', 'dir_ratio_bytes', 
    'avg_duration', 'avg_ttl'
  ]
  file_pattern: "*55.csv"
  test_size: 0.2
  random_state: 42
  outlier_removal: true
  handle_missing: true
